stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - docker login -u "gitlab-ci-token" -p "${CI_BUILD_TOKEN}" docker.sebbo.net
    - docker build -t docker.sebbo.net/fhws/grades-push .
    - docker push docker.sebbo.net/fhws/grades-push
  only:
    - master

publish_github:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/fhws-grades-push.git" --all
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/fhws-grades-push.git" --tags

deploy:
  stage: deploy
  tags:
    - matt.sebbo.net
    - ssh
  environment:
    name: production
  script:
    - docker login -u "gitlab-ci-token" -p "${CI_BUILD_TOKEN}" docker.sebbo.net
    - docker pull docker.sebbo.net/fhws/grades-push
  only:
    - master

trigger_dockerhub:
  stage: deploy
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - curl -q "https://registry.hub.docker.com/u/sebbo2002/fhws-grades-push/trigger/4a89a86f-5cdc-4e9f-a30d-811e474a75f7/"
  only:
    - master
